WEEKEND1/zad5/zad5_1/config/routes.rb
Rails.application.routes.draw do

  get 'tweets/status'

  get 'tweets/last'

  get 'people/new' => 'people#new'

  get 'people/add' => 'people#add'

  get 'tweets/show/:id' => 'tweets#show'

  get 'products/add' => 'products#add'
  get 'products/choice' => 'products#choice'
  get 'products/search' => 'products#search'
  get 'products/search_results' => 'products#search_results'
  get 'products/:id' => 'products#show'

  

end

WEEKEND1/zad5/zad5_1/app/models/person.rb
class Person < ActiveRecord::Base
	validates :name, :surname, presence: true
end

WEEKEND1/zad5/zad5_1/app/models/product.rb
class Product < ActiveRecord::Base
end

WEEKEND1/zad5/zad5_1/app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

WEEKEND1/zad5/zad5_1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

WEEKEND1/zad5/zad5_1/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
  end

  def add
  	person = Person.new(name: params[:name], surname: params[:surname])
  	if person.save
  		@added_succesfully = true
  	else
  		@added_succesfully = false	
  	end
  end
end

WEEKEND1/zad5/zad5_1/app/controllers/products_controller.rb
class ProductsController < ApplicationController
http_basic_authenticate_with name: "dag", password: "secret", only: :search	

	def show
		@product = Product.find(params[:id])
	end

	def add
		
	end

	def choice
		@name = params[:name]
		@language = params[:language]
	end

	def search

	end

	def search_results
		@products = Product.where(name: params[:name])
	end

end

WEEKEND1/zad5/zad5_1/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def show
  	@tweet = Tweet.find(params[:id])
  	render action: :status
  end

  def last
  	@tweet = Tweet.last
  	render action: :status
  end
end

WEEKEND1/zad5/zad5_1/app/helpers/application_helper.rb
module ApplicationHelper
end

WEEKEND1/zad5/zad5_1/app/helpers/people_helper.rb
module PeopleHelper
end

WEEKEND1/zad5/zad5_1/app/helpers/products_helper.rb
module ProductsHelper
end

WEEKEND1/zad5/zad5_1/app/helpers/tweets_helper.rb
module TweetsHelper
end

WEEKEND1/zad5/zad5_1/app/views/people/add.html.erb
<h1>People#add</h1>
<p>Find me in app/views/people/add.html.erb</p>

<% if @added_succesfully %>
<h1> Dodano </h1>

<% else %>
<h1> Niepoprawne dane </h1>

<%end%>

WEEKEND1/zad5/zad5_1/app/views/people/new.html.erb
<h1>People#new</h1>
<p>Find me in app/views/people/new.html.erb</p>

<%= form_tag(people_add_path, method: :get) do%>
<%= label_tag :name, "name: "%>
<%= text_field_tag :name %>
<%= label_tag :surname, "surname:" %>
<%= text_field_tag :surname %>
<%= submit_tag "Prześlij"%>

<%end%>

WEEKEND1/zad5/zad5_1/app/views/products/add.html.erb
<%= form_tag(products_choice_path, method: :get) do %>
<%= label_tag(:name, "Name: ") %>
<%= text_field_tag(:name) %>
<%= label_tag(:language, "Language: ") %>
<%= select_tag "language", "<option>Polish</option><option>English</option>".html_safe %>
<%= submit_tag("Prześlij") %>

<% end %>

WEEKEND1/zad5/zad5_1/app/views/products/choice.html.erb
<h1> your name is: <%=@name %> </h1>
<h2> your language: <%=@language%></h2>

WEEKEND1/zad5/zad5_1/app/views/products/search.html.erb
<%= form_tag(products_search_results_path, method: :get) do %>

<%= label_tag(:search, "search for: ")%>

<%= text_field_tag(:name)%>

<%= submit_tag "Prześlij"%>

<%end%>

WEEKEND1/zad5/zad5_1/app/views/products/search_results.html.erb
<% if @products.present? %>

<% @products.each do |p|%>
<h1> <%= p.name %> </h1>
<h2> <%= p.description %></h2>
<%end%>
<% else %>
<h1> Nie znaleziono elementu</h1>
<%end%>

WEEKEND1/zad5/zad5_1/app/views/products/show.html.erb
<h1> <%= @product.name %> </h1>
<h2> <%= @product.description %> </h2>